### ISSUE TITLE
App does not work on docomo F-04K

### ISSUE THREAD

**Issue by huideyeren** [kazumihirose/Covid19Radar#68]
App does not work on docomo F-04K.
The initial screen does not start even if I repeat it.
The splash will be displayed, but at that point the app will collapse.
The app is build number 88 downloaded from the App Center.

（以下日本語）
docomo F-04K（らくらくスマートフォン）でAPKが起動直後に停止します。
何度繰り返しても初期画面が起動しません。
スプラッシュは表示されますが、その時点でアプリがおちてしまいます。
アプリはApp Centerからダウンロードしたビルド番号88のものです。

**Comment by snickerjp** [comment]
同じくAndroid App起動しません。
ビルド番号89です。

* Pixel3
* OPPO Reno A

で、試しました。

**Comment by kazumihirose** [comment]
ありがとうございます。ちょっと、コアチームの方でも確認して、原因あたってみます。

**Comment by takuya1981** [comment]
同じく起動しません。
ビルド番号89です。
試したのは以下の機種です。
- Blackview A60 Pro

**Comment by takuya1981** [comment]
While launching app, the following log is output in AndroidStudio.
2020-04-17 18:25:36.818 13399-13399/net.kzmx.Covid19Radar E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.kzmx.Covid19Radar, PID: 13399
    java.lang.RuntimeException: Unable to get provider mono.MonoRuntimeProvider: java.lang.RuntimeException: Unable to find application Mono.Android.Platform.ApiLevel_28!
        at android.app.ActivityThread.installProvider(ActivityThread.java:6427)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5969)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5884)
        at android.app.ActivityThread.access$1200(ActivityThread.java:206)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1678)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6702)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
     Caused by: java.lang.RuntimeException: Unable to find application Mono.Android.Platform.ApiLevel_28!
        at mono.MonoRuntimeProvider.attachInfo(MonoRuntimeProvider.java:38)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6422)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5969) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5884) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:206) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1678) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6702) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911) 
     Caused by: android.content.pm.PackageManager$NameNotFoundException: Mono.Android.Platform.ApiLevel_28
        at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:395)
        at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:377)

**Comment by Sakkuuu1818** [comment]
下記端末でも起動しませんでした
　Pixel3a XL（Android10）
　ビルド番号90

**Comment by kazumihirose** [comment]
ビルド証明書の修正を行いました。ご確認頂けましたら幸いです。
---
Fixed the build certificate.  We would appreciate it if you could re-install and check.

**Comment by takapi-Jr** [comment]
スタート画面の表示がされました。

The start screen is displayed.
Zenfone 2(Android 6.0.1)→OK
Zenfone 4(Android 8.0.0)→OK
Build Number 100

**Comment by takuya1981** [comment]
起動しました。
- Blackview A60 Pro

**Comment by huideyeren** [comment]
起動しました。
docomo F-04K
Build Number: 101

**Comment by Sakkuuu1818** [comment]
起動できました。
Pixel3a XL（Android10）
ビルド番号101

**Comment by snickerjp** [comment]
起動しました

* ビルド番号101
* OPPO Reno A
